version: "1"
packages:
  - name: "expstore"
    path: ".."
    queries: "../queries"
    schema: "../schema"
    engine: "postgresql"
    emit_prepared_queries: true
    emit_interface: true
    emit_exact_table_names: true
    emit_empty_slices: true
    emit_json_tags: true
    json_tags_case_style: "camel"
